version: '3.8'

services:
  crud_docker:
    build: .
    volumes:
      - .:/crud_docker
    environment:
      - DATABASE_TYPE=${DB_TYPE}
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
      - DATABASE_USERNAME=${DB_USERNAME}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - DATABASE_DATABASE=${DB_DATABASE}
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_TYPE: ${DB_TYPE}

    ports:
      - "5432:5432"
